name: Docker build dev deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker authentication
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker image build
        run: docker build -t anilgadwal/reactjs-auth .

      - name: Push docker image to dockerhub
        run: docker push anilgadwal/reactjs-auth
