name: Docker build dev deployment

on:
  push:
    branches:
      - main

env:
  IMAGE: anilgadwal/reactjs-auth

jobs:
  build:
    name: Push to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Docker authentication
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker image build
        run: docker build -t ${{ env.IMAGE }} -f Dockerfile.

      - name: Push docker image to dockerhub
        run: docker push ${{ env.IMAGE }}
